#pragma once

// JavaScript for the file browser UI. The placeholder {API_BASE} is replaced at
// runtime with the configured url_prefix before serving.
static constexpr const char HTTP_FILE_BROWSER_JS[] = R"JS(
function fmt_size(b){if(b<1024)return b+' B';if(b<1048576)return (b/1024).toFixed(1)+' KB';if(b<1073741824)return (b/1048576).toFixed(1)+' MB';return (b/1073741824).toFixed(1)+' GB';}
function show_progress(title){document.getElementById('progressTitle').textContent=title;document.getElementById('progressBar').style.width='0%';document.getElementById('progressBar').textContent='0%';document.getElementById('progressDetails').textContent='Initializing...';document.getElementById('progressSpeed').textContent='';document.getElementById('progressSource').textContent='-';document.getElementById('progressDest').textContent='-';document.getElementById('progressModal').classList.add('active');poll_progress();}
function hide_progress(){document.getElementById('progressModal').classList.remove('active');}
let progressInterval=null;
function poll_progress(){if(progressInterval)clearInterval(progressInterval);progressInterval=setInterval(async()=>{try{const r=await fetch(API_BASE+'/api/progress');const d=await r.json();if(!d.in_progress){clearInterval(progressInterval);progressInterval=null;hide_progress();location.reload();return;}const pct=d.percentage||0;document.getElementById('progressBar').style.width=pct+'%';document.getElementById('progressBar').textContent=pct.toFixed(1)+'%';if(d.source)document.getElementById('progressSource').textContent=d.source;if(d.destination)document.getElementById('progressDest').textContent=d.destination;if(d.avg_speed)document.getElementById('progressSpeed').textContent='Speed: '+fmt_size(d.avg_speed)+'/s';}catch(e){}},500);}
async function cancelOperation(){try{await fetch(API_BASE+'/api/cancel',{method:'POST'});hide_progress();}catch(e){}}
function download_file(uri,name){const a=document.createElement('a');a.href=uri;a.download=name;document.body.appendChild(a);a.click();document.body.removeChild(a);}
async function delete_file(path){if(!confirm('Delete file '+path+'?'))return;try{const r=await fetch(API_BASE+'/api/delete',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'path='+encodeURIComponent(path)});const d=await r.json();if(d.success)location.reload();else alert('Delete failed: '+(d.error||'Unknown error'));}catch(e){alert('Error: '+e);}}
async function delete_directory(path){if(!confirm('Delete directory '+path+' and all contents?'))return;try{const r=await fetch(API_BASE+'/api/delete',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'path='+encodeURIComponent(path)});const d=await r.json();if(d.success){show_progress('Deleting...');location.reload();}else alert('Delete failed: '+(d.error||'Unknown error'));}catch(e){alert('Error: '+e);}}
async function create_directory(){const name=prompt('Enter directory name:');if(!name)return;const current=window.location.pathname;try{const r=await fetch(API_BASE+'/api/mkdir',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'name='+encodeURIComponent(current+'/'+name)});const d=await r.json();if(d.success)location.reload();else alert('Failed: '+(d.error||'Unknown error'));}catch(e){alert('Error: '+e);}}
async function rename_file(path){const name=prompt('New name:',path.split('/').pop());if(!name)return;try{const r=await fetch(API_BASE+'/api/rename',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'source='+encodeURIComponent(path)+'&name='+encodeURIComponent(name)});const d=await r.json();if(d.success)location.reload();else alert('Rename failed: '+(d.error||'Unknown error'));}catch(e){alert('Error: '+e);}}
async function copy_file(path){const dest=prompt('Copy to path:',path);if(!dest||dest===path)return;show_progress('Copying...');try{const r=await fetch(API_BASE+'/api/copy',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'source='+encodeURIComponent(path)+'&destination='+encodeURIComponent(dest)});const d=await r.json();if(!d.success){hide_progress();alert('Copy failed: '+(d.error||'Unknown error'));}}catch(e){hide_progress();alert('Error: '+e);}}
async function move_file(path){const dest=prompt('Move to path:',path);if(!dest||dest===path)return;show_progress('Moving...');try{const r=await fetch(API_BASE+'/api/move',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'source='+encodeURIComponent(path)+'&destination='+encodeURIComponent(dest)});const d=await r.json();if(!d.success){hide_progress();alert('Move failed: '+(d.error||'Unknown error'));}}catch(e){hide_progress();alert('Error: '+e);}}
async function show_file_info(path){try{const r=await fetch(API_BASE+'/api/fileinfo?path='+encodeURIComponent(path));const d=await r.json();if(d.error){alert('Error: '+d.error);return;}let msg='Name: '+d.name+'\nPath: '+d.path+'\nSize: '+fmt_size(d.size)+'\nType: '+(d.is_directory?'Directory':'File')+'\nStorage: '+d.storage_type;alert(msg);}catch(e){alert('Error: '+e);}}
async function mount_device(path){try{const r=await fetch(API_BASE+'/api/mount',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'mount_point='+encodeURIComponent(path)});const d=await r.json();if(d.success)setTimeout(()=>location.reload(),500);else alert('Mount failed: '+(d.error||'Unknown error'));}catch(e){alert('Error: '+e);}}
async function unmount_device(path){try{const r=await fetch(API_BASE+'/api/unmount',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'mount_point='+encodeURIComponent(path)});const d=await r.json();if(d.success)setTimeout(()=>location.reload(),500);else alert('Unmount failed: '+(d.error||'Unknown error'));}catch(e){alert('Error: '+e);}}
async function remount_device(path){try{const r=await fetch(API_BASE+'/api/remount',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'mount_point='+encodeURIComponent(path)});const d=await r.json();if(d.success)setTimeout(()=>location.reload(),500);else alert('Remount failed: '+(d.error||'Unknown error'));}catch(e){alert('Error: '+e);}}
async function handleUpload(event){event.preventDefault();const file=document.getElementById('uploadFile').files[0];if(!file)return false;const CHUNK=65536;const total=Math.ceil(file.size/CHUNK);show_progress('Uploading '+file.name+'...');for(let i=0;i<total;i++){const blob=file.slice(i*CHUNK,(i+1)*CHUNK);const fd=new FormData();fd.append('filename',file.name);fd.append('chunkIndex',i);fd.append('totalChunks',total);fd.append('path',window.location.pathname.replace(API_BASE,''));fd.append('fileSize',file.size);fd.append('chunk',blob);try{const r=await fetch(API_BASE+'/api/upload_chunk',{method:'POST',body:fd});const d=await r.json();if(!d.success&&!d.cancelled){hide_progress();alert('Upload failed');return false;}}catch(e){hide_progress();alert('Upload error: '+e);return false;}}hide_progress();location.reload();return false;}
)JS";
